USE [master]
GO
/****** Object:  Database [SistemaI4]    Script Date: 3/14/2022 11:49:10 PM ******/
CREATE DATABASE [SistemaI4]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SistemaI4', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SistemaI4.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SistemaI4_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SistemaI4_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SistemaI4] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SistemaI4].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SistemaI4] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SistemaI4] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SistemaI4] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SistemaI4] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SistemaI4] SET ARITHABORT OFF 
GO
ALTER DATABASE [SistemaI4] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [SistemaI4] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SistemaI4] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SistemaI4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SistemaI4] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SistemaI4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SistemaI4] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SistemaI4] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SistemaI4] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SistemaI4] SET  ENABLE_BROKER 
GO
ALTER DATABASE [SistemaI4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SistemaI4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SistemaI4] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SistemaI4] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SistemaI4] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SistemaI4] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SistemaI4] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SistemaI4] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SistemaI4] SET  MULTI_USER 
GO
ALTER DATABASE [SistemaI4] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SistemaI4] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SistemaI4] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SistemaI4] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SistemaI4] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SistemaI4] SET QUERY_STORE = OFF
GO
USE [SistemaI4]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [SistemaI4]
GO
/****** Object:  User [SysfacWeiser1]    Script Date: 3/14/2022 11:49:10 PM ******/
CREATE USER [SysfacWeiser1] FOR LOGIN [SysfacWeiser1] WITH DEFAULT_SCHEMA=[SysfacWeiser1]
GO
/****** Object:  User [itninnova]    Script Date: 3/14/2022 11:49:10 PM ******/
CREATE USER [itninnova] FOR LOGIN [itninnova] WITH DEFAULT_SCHEMA=[itninnova]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [SysfacWeiser1]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [SysfacWeiser1]
GO
ALTER ROLE [db_datareader] ADD MEMBER [SysfacWeiser1]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [SysfacWeiser1]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [itninnova]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [itninnova]
GO
ALTER ROLE [db_datareader] ADD MEMBER [itninnova]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [itninnova]
GO
/****** Object:  Schema [itninnova]    Script Date: 3/14/2022 11:49:10 PM ******/
CREATE SCHEMA [itninnova]
GO
/****** Object:  Schema [SysfacWeiser1]    Script Date: 3/14/2022 11:49:10 PM ******/
CREATE SCHEMA [SysfacWeiser1]
GO
/****** Object:  Table [dbo].[tBasculas]    Script Date: 3/14/2022 11:49:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tBasculas](
	[ID_Bascula] [varchar](25) NOT NULL,
	[Descripcion] [varchar](250) NULL,
 CONSTRAINT [PK_tBasculas] PRIMARY KEY CLUSTERED 
(
	[ID_Bascula] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tBOM]    Script Date: 3/14/2022 11:49:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tBOM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_Producto] [varchar](25) NULL,
	[ID_Componente] [varchar](25) NULL,
	[Cantidad] [decimal](18, 7) NULL,
 CONSTRAINT [PK_tBOM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tComponentes]    Script Date: 3/14/2022 11:49:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tComponentes](
	[ID_Componente] [varchar](25) NOT NULL,
	[Descripcion] [varchar](250) NULL,
	[PesoUnitarioGramos] [decimal](18, 7) NULL,
	[Minimo] [decimal](18, 7) NULL,
	[Maximo] [decimal](18, 7) NULL,
	[Imagen] [image] NULL,
 CONSTRAINT [PK_tComponentes] PRIMARY KEY CLUSTERED 
(
	[ID_Componente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tInventario]    Script Date: 3/14/2022 11:49:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tInventario](
	[ID_Componente] [varchar](25) NULL,
	[ID_Bascula] [varchar](25) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tLineasComponentesBasculas]    Script Date: 3/14/2022 11:49:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tLineasComponentesBasculas](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_Linea] [varchar](25) NULL,
	[ID_Componente] [varchar](25) NULL,
	[ID_Bascula] [varchar](25) NULL,
 CONSTRAINT [PK_tIneasComponentesBasculas] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tLineasProduccion]    Script Date: 3/14/2022 11:49:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tLineasProduccion](
	[ID_Linea] [varchar](25) NOT NULL,
	[Descripcion] [varchar](25) NULL,
 CONSTRAINT [PK_tLineasProduccion] PRIMARY KEY CLUSTERED 
(
	[ID_Linea] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tProductos]    Script Date: 3/14/2022 11:49:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tProductos](
	[ID_Producto] [varchar](25) NOT NULL,
	[Descripcion] [varchar](250) NULL,
	[Imagen] [image] NULL,
 CONSTRAINT [PK_tProductos] PRIMARY KEY CLUSTERED 
(
	[ID_Producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tUsuarios]    Script Date: 3/14/2022 11:49:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tUsuarios](
	[ID_Usuario] [varchar](250) NOT NULL,
	[Nombre] [varchar](250) NULL,
	[EMail] [varchar](250) NULL,
 CONSTRAINT [PK_tUsuarios] PRIMARY KEY CLUSTERED 
(
	[ID_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tBOM]  WITH CHECK ADD  CONSTRAINT [FK_tBOM_tComponentes] FOREIGN KEY([ID_Componente])
REFERENCES [dbo].[tComponentes] ([ID_Componente])
GO
ALTER TABLE [dbo].[tBOM] CHECK CONSTRAINT [FK_tBOM_tComponentes]
GO
ALTER TABLE [dbo].[tBOM]  WITH CHECK ADD  CONSTRAINT [FK_tBOM_tProductos] FOREIGN KEY([ID_Producto])
REFERENCES [dbo].[tProductos] ([ID_Producto])
GO
ALTER TABLE [dbo].[tBOM] CHECK CONSTRAINT [FK_tBOM_tProductos]
GO
ALTER TABLE [dbo].[tLineasComponentesBasculas]  WITH CHECK ADD  CONSTRAINT [FK_tLineasComponentesBasculas_tBasculas] FOREIGN KEY([ID_Bascula])
REFERENCES [dbo].[tBasculas] ([ID_Bascula])
GO
ALTER TABLE [dbo].[tLineasComponentesBasculas] CHECK CONSTRAINT [FK_tLineasComponentesBasculas_tBasculas]
GO
ALTER TABLE [dbo].[tLineasComponentesBasculas]  WITH CHECK ADD  CONSTRAINT [FK_tLineasComponentesBasculas_tComponentes] FOREIGN KEY([ID_Componente])
REFERENCES [dbo].[tComponentes] ([ID_Componente])
GO
ALTER TABLE [dbo].[tLineasComponentesBasculas] CHECK CONSTRAINT [FK_tLineasComponentesBasculas_tComponentes]
GO
ALTER TABLE [dbo].[tLineasComponentesBasculas]  WITH CHECK ADD  CONSTRAINT [FK_tLineasComponentesBasculas_tLineasProduccion] FOREIGN KEY([ID_Linea])
REFERENCES [dbo].[tLineasProduccion] ([ID_Linea])
GO
ALTER TABLE [dbo].[tLineasComponentesBasculas] CHECK CONSTRAINT [FK_tLineasComponentesBasculas_tLineasProduccion]
GO
USE [master]
GO
ALTER DATABASE [SistemaI4] SET  READ_WRITE 
GO
